name: issue_triage_bot
description: A triage automation tool for issues.

publish_to: none

environment:
  sdk: '>=3.10.0 <3.11.0'

dependencies:
  args: 2.7.0
  github: 9.25.0
  google_generative_ai: 0.4.7
  graphql: 5.2.3
  http: 1.6.0

dev_dependencies:
  flutter_lints: 6.0.0
